apiVersion: v1
kind: Service
metadata:
  name: punchpoint-service
spec:
  type: LoadBalancer  # Creates an external load balancer
  selector:
    app: punchpoint
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000